In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv('C:\\Users\\byeby\\Desktop\\cz4041\\train.csv')

In [3]:
data

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,...,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month,target
0,0,0,0,0,T,Y,Green,Triangle,Snake,Finland,...,2f4cb3d51,2,Grandmaster,Cold,h,D,kr,2,2,0
1,1,0,1,0,T,Y,Green,Trapezoid,Hamster,Russia,...,f83c56c21,1,Grandmaster,Hot,a,A,bF,7,8,0
2,2,0,0,0,F,Y,Blue,Trapezoid,Lion,Russia,...,ae6800dd0,1,Expert,Lava Hot,h,R,Jc,7,2,0
3,3,0,1,0,F,Y,Red,Trapezoid,Snake,Canada,...,8270f0d71,1,Grandmaster,Boiling Hot,i,D,kW,2,1,1
4,4,0,0,0,F,N,Red,Trapezoid,Lion,Canada,...,b164b72a7,1,Grandmaster,Freezing,a,R,qP,7,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,299995,0,0,0,T,N,Red,Trapezoid,Snake,India,...,e027decef,1,Contributor,Freezing,k,K,dh,3,8,0
299996,299996,0,0,0,F,Y,Green,Trapezoid,Lion,Russia,...,80f1411c8,2,Novice,Freezing,h,W,MO,3,2,0
299997,299997,0,0,0,F,Y,Blue,Star,Axolotl,Russia,...,314dcc15b,3,Novice,Boiling Hot,o,A,Bn,7,9,1
299998,299998,0,1,0,F,Y,Green,Square,Axolotl,Costa Rica,...,ab0ce192b,1,Master,Boiling Hot,h,W,uJ,3,8,1
299999,299999,0,0,0,F,Y,Blue,Trapezoid,Dog,Russia,...,ad1af2b45,3,Contributor,Freezing,i,R,tP,1,3,0

In [4]:
trainX,trainY = data.iloc[:,0:24],data.iloc[:,-1]
print(trainX.shape[0],trainX.shape[1])

300000 24

In [5]:
trainX

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,...,nom_8,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month
0,0,0,0,0,T,Y,Green,Triangle,Snake,Finland,...,c389000ab,2f4cb3d51,2,Grandmaster,Cold,h,D,kr,2,2
1,1,0,1,0,T,Y,Green,Trapezoid,Hamster,Russia,...,4cd920251,f83c56c21,1,Grandmaster,Hot,a,A,bF,7,8
2,2,0,0,0,F,Y,Blue,Trapezoid,Lion,Russia,...,de9c9f684,ae6800dd0,1,Expert,Lava Hot,h,R,Jc,7,2
3,3,0,1,0,F,Y,Red,Trapezoid,Snake,Canada,...,4ade6ab69,8270f0d71,1,Grandmaster,Boiling Hot,i,D,kW,2,1
4,4,0,0,0,F,N,Red,Trapezoid,Lion,Canada,...,cb43ab175,b164b72a7,1,Grandmaster,Freezing,a,R,qP,7,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,299995,0,0,0,T,N,Red,Trapezoid,Snake,India,...,7508f4ef1,e027decef,1,Contributor,Freezing,k,K,dh,3,8
299996,299996,0,0,0,F,Y,Green,Trapezoid,Lion,Russia,...,397dd0274,80f1411c8,2,Novice,Freezing,h,W,MO,3,2
299997,299997,0,0,0,F,Y,Blue,Star,Axolotl,Russia,...,5d7806f53,314dcc15b,3,Novice,Boiling Hot,o,A,Bn,7,9
299998,299998,0,1,0,F,Y,Green,Square,Axolotl,Costa Rica,...,1f820c7ce,ab0ce192b,1,Master,Boiling Hot,h,W,uJ,3,8
299999,299999,0,0,0,F,Y,Blue,Trapezoid,Dog,Russia,...,c13d3ebdf,ad1af2b45,3,Contributor,Freezing,i,R,tP,1,3

In [6]:
trainY

0         0
1         0
2         0
3         1
4         0
         ..
299995    0
299996    0
299997    1
299998    1
299999    0
Name: target, Length: 300000, dtype: int64

In [7]:
trainLabelX = pd.DataFrame()
label=LabelEncoder()
for c in trainX.columns:
    if(trainX[c].dtype == 'object'):
        trainLabelX[c] = label.fit_transform(trainX[c])
    else:
        trainLabelX[c] = trainX[c]

In [8]:
from sklearn.linear_model import LogisticRegression as lg
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


X_train,X_test,y_train,y_test=train_test_split(trainLabelX,trainY,random_state=42,test_size=0.2)
lr=lg()
lr.fit(X_train,y_train)
y_pre=lr.predict(X_test)
print(accuracy_score(y_test,y_pre))

0.69065

In [9]:
testX = pd.read_csv('C:\\Users\\byeby\\Desktop\\cz4041\\test.csv')
testXlabel = pd.DataFrame()
for c in testX.columns:
    if testX[c].dtype == 'object':
        testXlabel[c] = label.fit_transform(testX[c])
    else:
        testXlabel[c] = testX[c]
print(testX.shape[0],testX.shape[1])

200000 24

In [10]:
test_target = lr.predict_proba(testXlabel)[:,1]
test_target

array([0.33235947, 0.34732511, 0.42370532, ..., 0.32853179, 0.15632708,
       0.23657657])

In [11]:
submission = pd.read_csv('C:\\Users\\byeby\\Desktop\\cz4041\\sample_submission.csv')
submission['target'] = test_target
submission.to_csv('label_model.csv')

submission

            id    target
0       300000  0.332359
1       300001  0.347325
2       300002  0.423705
3       300003  0.334584
4       300004  0.242730
...        ...       ...
199995  499995  0.128803
199996  499996  0.128996
199997  499997  0.328532
199998  499998  0.156327
199999  499999  0.236577

[200000 rows x 2 columns]